const default_residents = [
  {
    first_name: "Alex",
    last_name: "Salinas",
    room: "West 35",
    age: 87,
    battery: 70,
    status: "Awake",
    location: "Cafeteria",
    resident_id: 1,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Screened Porch", "10:00 AM", "11:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Activity Room", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Evelyn",
    last_name: "Davis",
    room: "East 66",
    age: 95,
    battery: 45,
    status: "Awake",
    location: "Cafeteria",
    resident_id: 2,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Screened Porch", "10:00 AM", "11:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Den", "3:00 PM", "4:00 PM"],
      ["Activity Room", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Harold",
    last_name: "Parker",
    room: "West 36",
    age: 86,
    battery: 67,
    status: "Awake",
    location: "Cafeteria",
    resident_id: 3,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Hearth Room", "10:00 AM", "12:00 PM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Den", "3:00 PM", "4:00 PM"],
      ["Activity Room", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Jack",
    last_name: "Jacobs",
    room: "North 311",
    age: 102,
    battery: 78,
    status: "Awake",
    location: "Cafeteria",
    resident_id: 4,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Activity Room", "10:00 AM", "11:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Activity Room", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Jess",
    last_name: "Lutz",
    room: "North 312",
    age: 98,
    battery: 68,
    status: "Awake",
    location: "Cafeteria",
    resident_id: 5,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Den", "10:00 AM", "11:30 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Den", "2:00 PM", "4:00 PM"],
      ["Screened Porch", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Mike",
    last_name: "Kent",
    room: "East 67",
    age: 99,
    battery: 46,
    status: "Active",
    location: "Outside Facility",
    resident_id: 6,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Screened Porch", "10:00 AM", "11:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Activity Room", "4:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Nick",
    last_name: "Miller",
    room: "West 37",
    age: 84,
    battery: 89,
    status: "Asleep",
    location: "Cafeteria",
    resident_id: 7,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Activity Room", "10:00 AM", "11:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Screened Porch", "3:00 PM", "4:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Stanley",
    last_name: "Sherman",
    room: "North 313",
    age: 82,
    battery: 75,
    status: "Asleep",
    location: "Room",
    resident_id: 8,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Hearth Room", "10:00 AM", "12:00 PM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Screened Porch", "3:00 PM", "4:00 PM"],
      ["Activity Room", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
  {
    first_name: "Susie",
    last_name: "Takeda",
    room: "East 68",
    age: 90,
    battery: 81,
    status: "Agitated",
    location: "Cafeteria",
    resident_id: 9,
    common_locations: [
      ["Dining Room", "8:00 AM", "9:00 AM"],
      ["Dining Room", "12:00 PM", "1:00 PM"],
      ["Den", "2:00 PM", "3:00 PM"],
      ["Screened Porch", "5:00 PM", "6:00 PM"],
      ["Dining Room", "6:00 PM", "7:00 PM"],
    ],
  },
];

export default default_residents;
