const resident_locations = {
  "-1": {
    Alex: "Screened Porch",
    Evelyn: "Screened Porch",
    Harold: "Hearth Room",
    Jack: "Activity Room",
    Jess: "Den",
    Mike: "Screened Porch",
    Nick: "Activity Room",
    Stanley: "Hearth Room",
    Susie: "Bedroom",
  },
  0: {
    Alex: "Screened Porch",
    Evelyn: "Screened Porch",
    Harold: "Hearth Room",
    Jack: "Activity Room",
    Jess: "Den",
    Mike: "Screened Porch",
    Nick: "Activity Room",
    Stanley: "Hearth Room",
    Susie: "Bedroom",
  },
  1: {
    Alex: "Dining Room",
    Evelyn: "Dining Room",
    Harold: "Dining Room",
    Jack: "Dining Room",
    Jess: "Bedroom",
    Mike: "Bedroom",
    Nick: "Bedroom",
    Stanley: "Dining Room",
    Susie: "Dining Room",
  },
  2: {
    Alex: "Screened Porch",
    Evelyn: "Screened Porch",
    Harold: "Hearth Room",
    Jack: "Activity Room",
    Jess: "Den",
    Mike: "Screened Porch",
    Nick: "Activity Room",
    Stanley: "Hearth Room",
    Susie: "Bedroom",
  },
  3: {
    Alex: "Bedroom",
    Evelyn: "Activity Room",
    Harold: "Dining Room",
    Jack: "Activity Room",
    Jess: "Screened Porch",
    Mike: "Bedroom",
    Nick: "Bedroom",
    Stanley: "Dining Room",
    Susie: "Screened Porch",
  },
  4: {
    Alex: "Bedroom",
    Evelyn: "Bedroom",
    Harold: "Bedroom",
    Jack: "Bedroom",
    Jess: "Bedroom",
    Mike: "Bedroom",
    Nick: "Bedroom",
    Stanley: "Bedroom",
    Susie: "Bedroom",
  },
  5: {
    Alex: "Bedroom",
    Evelyn: "Bedroom",
    Harold: "Bedroom",
    Jack: "Bedroom",
    Jess: "Bedroom",
    Mike: "Bedroom",
    Nick: "Bedroom",
    Stanley: "Bedroom",
    Susie: "Bedroom",
  },
  6: {
    Alex: "Screened Porch",
    Evelyn: "Screened Porch",
    Harold: "Hearth Room",
    Jack: "Activity Room",
    Jess: "Den",
    Mike: "Screened Porch",
    Nick: "Activity Room",
    Stanley: "Hearth Room",
    Susie: "Bedroom",
  },
};

export default resident_locations;
